### ISSUE TITLE
Is this even OK...

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/node-lowlevel-keyboard-hook-win#1]
@paulcbetts

Sorry for tagging you but you seem to know what you are on about with a lot of these things.  
I couldn't make low level keyboard hooks work from within a native node module so I came up with this compromise thing.

I'm not sure whether this is a good idea in any way (spawning a exe file who's sole purpose is to listen for key events).

I was wondering what your opinion on this solution is?

**Comment by anaisbetts** [comment]
Hm, this should work from a node module but might not if you're testing it from a console node process (which you probably were). You should definitely do that instead of trying to run it as a separate executable.

Another thing you need to do is, hooks need to be FAST - all you should do in a keyboard hook is add an item to a list, and you should have another thread (or better yet, schedule a libuv event) to clear out that list and run the JavaScript callback. If you take too long in a hook (i.e. if you were to do the naive thing of just immediately running the JS callback), Windows will actually remove your hook.

**Comment by MarshallOfSound** [comment]
Time to crack onto the C++ then :disappointed: 

Not my favourite past time :smile:

**Comment by MarshallOfSound** [comment]
@paulcbetts I'm sure you live my messages :)

Do you know of an example usage of `uv_thread_create` combined with `uv_async_send`.  I can find people all over the place telling me to use them, but not a single example in sight.

Thanks for you help :+1:

**Comment by anaisbetts** [comment]
@MarshallOfSound atom/keyboard_layout has at least uv_async_send

**Comment by MarshallOfSound** [comment]
Hey @paulcbetts 

i've made some real progress on this and I swear I'm like one line off it working.

However for some reason (my c++ is bad is probably the reason) this line causes it to crash with no error message.

https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win/blob/no-exe/ll_keyboard_hooks.cc#L75

Do you have ANY idea why that is happening, it's been making me crazy for a while now

**Comment by anaisbetts** [comment]
> However for some reason (my c++ is bad is probably the reason) this line causes it to crash with no error message.

You're probably hitting a V8 assert, which has the obnoxious behavior of just killing everything. Do you have repro steps on how to get into that code?

**Comment by MarshallOfSound** [comment]
Assuming you mean how to get execution into that block

Cloning, checking out thr `no-exe` branch and running. 

``` bash
npm install && node ll_keyboard_hooks.js
```

Then just hit any key on your keyboard and the hook will file and call that async method, then it will crash

**Comment by MarshallOfSound** [comment]
@paulcbetts OK, so now I've gotten to the point where the silent fail is gone but now I am getting node.js lifecycle errors....

``` js
14 verbose stack Error: callbacks@0.0.0 start: `npm build . && node ll_keyboard_hooks.js`
14 verbose stack Exit status 3221225477
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid callbacks@0.0.0
```

This is slowly killing me, any ideas :+1:

**Comment by MarshallOfSound** [comment]
Never mind, I got it working, turns out I had to use a persistent function :+1: 

Thanks for all the help @paulcbetts  You da best :+1:

**Comment by anaisbetts** [comment]
:sparkles:
