### ISSUE TITLE
how monitor alt+f4 keys?

### ISSUE THREAD

**Issue by niufwshd** [MarshallOfSound/node-lowlevel-keyboard-hook-win#2]
@MarshallOfSound ,I have a electron app,and want to disable alt+f4 ,but I don't know to deal the composed keycode! can you give me any suggestion or example, thank you very much first!

**Comment by MarshallOfSound** [comment]
The key codes you get from this module are vkcodes, see the full list here

http://www.kbdedit.com/manual/low_level_vk_list.html

**Comment by niufwshd** [comment]
@MarshallOfSound  thank you for your quick reply!   I mean I must deal two vkcode one time not one!
I have read the [readme](https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win).it have a statement  'NOTE: keyCode has to be a vkCode or "*" '. I don't know how to compose two vkcode,can you help me?
